# General settings
notifications:
  email: false
sudo: false
dist: trusty

# Build matrix
os:
  - linux
  - osx
language: cpp
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
      compiler: gcc

# Install, build, and test
addons:
  apt:
    packages:
      - cmake
      - lcov
cache:
  directories:
    - $HOME/yaml-cpp-0.6.2

install:
  - which $CXX
  - $CXX --version
  # yaml-cpp
  - export YAML_CPP_DIR="$HOME/yaml-cpp-0.6.2"
  - |
    # Check cache
    if [ ! -e "$YAML_CPP_DIR/include/yaml-cpp/yaml.h" ]; then
      (
        mkdir -p external
        cd external
        echo GETTING
        wget https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz
        echo UNPACKING
        tar xzf yaml-cpp-0.6.2.tar.gz
        echo PATCHING
        (cd yaml-cpp-yaml-cpp-0.6.2 && patch -p1 "../../easier-to-inherit.diff")
        echo BUILDING
        mkdir yaml-cpp-0.6.2-build
        cd yaml-cpp-0.6.2-build
        cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="$YAML_CPP_DIR" "../yaml-cpp-yaml-cpp-0.6.2"
        make -j2
        make -j2 install
      )
    fi
  # Python
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      export PYTHON_DIR="/usr"
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = osx ]; then
      brew update
      brew install lcov
      export PYTHON_DIR="/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7"
      export PATH="/usr/local/Cellar/python/2.7.14/bin:$PATH"
    fi
  - hash -r
  - which python
  - python --version
  # Coverage
  - pip install --user codecov
  - gem install coveralls-lcov
  - which lcov
  - lcov --version
  - mkdir -p "$HOME/bin"
  - ln -s "$(which $GCOV)" "$HOME/bin/gcov"
  - ls -l "$HOME/bin"
  - export PATH="$HOME/bin:$PATH"
  - hash -r

script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_PREFIX_PATH="$YAML_CPP_DIR" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - make -j2
  - make -j2 test CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 install
  - popd

after_success:
  - mkdir build-coveralls && pushd build-coveralls
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN='u0rrEwxLGB0FeUrfeA4zdqr9hD6lyOyyx'
  - cmake -DCMAKE_PREFIX_PATH="$YAML_CPP_DIR" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
  - make -j2
  - make -j2 coveralls CTEST_OUTPUT_ON_FAILURE=1
  - popd
